export const SET_AVAILABLE_JOBS = "SET_AVAILABLE_JOBS";
export const SET_APPLIED_JOBS = "SET_APPLIED_JOBS";
export const APPY_TO_JOB = "APPY_TO_JOB";
export const LOADING = "LOADING";
export const AVAILABLE_JOBS_LOADING = "AVAILABLE_JOBS_LOADING";
export const APPLIED_JOBS_LOADING = "APPLIED_JOBS_LOADING";
export const ERROR = "ERROR";
export const RESET_DATA = "RESET_DATA";
